# Generated by Django 5.0.7 on 2024-07-20 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="published_date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
    ]
