# Generated by Django 5.0.7 on 2024-07-20 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="updated_at",
        ),
    ]
